name: badign_app
description: iTechEvent central application for doctors, participants and event staff.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  # HTTP client
  dio: ^5.4.0
  # State management
  provider: ^6.1.2
  # Local storage (token, prefs)
  shared_preferences: ^2.2.3
  # Barcode / QR scanner
  mobile_scanner: ^5.1.1
  # Date formatting
  intl: ^0.19.0
  # Icons
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_animate: ^4.5.2
  url_launcher: ^6.3.2
  liquid_glass_widgets: ^1.2.3
  youtube_player_iframe: ^6.0.2
  add_2_calendar: 3.0.1
  pdfrx: ^2.4.7
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/home/
    - assets/branding/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
